### ISSUE TITLE
Issue when uploading results

### ISSUE THREAD

**Issue by kahnchana** [valeoai/bravo_challenge#4]
When uploading the results, we seem to get the following error with no additional info. Has anyone faced this problem? 

Trying to figure out why this may be happening. 

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/3d57c58c-971d-4d1d-9462-c347de933958">

**Comment by tuanhungvu** [comment]
Hello @kahnchana , 
The error is quite weird. Can you share the log when encoding your submission ([guide](https://github.com/valeoai/bravo_challenge?tab=readme-ov-file#432-encoding-the-submission-files-to-the-submission-format))?

**Comment by kahnchana** [comment]
Hi @tuanhungvu 

Thanks a lot for the quick response! This is the log I get when running the encoding script:

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/c730ee9a-3565-4674-990a-1ac76d40b74c">

**Comment by kahnchana** [comment]
I run it from the directory and my root directory has an identical tree structure to the one on the repo appendix.  
[dir_tree.txt](https://github.com/user-attachments/files/16732760/dir_tree.txt)

**Comment by tuanhungvu** [comment]
We contacted @kahnchana and discovered that the error was caused by out-of-range predictions. To prevent this issue, participants should load the _pred.png file using cv2 with the cv2.IMREAD_GRAYSCALE flag, and verify that the prediction values fall within the [0,18] range.
 
`pred = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)
`
